version: "3.8"

services:
  flask-app:
    image: flask-app-arm
    ports:
      - "5000:5000"
    volumes:
      - /host/folder:/container/folder
    entrypoint: ["python", "main.py","--path", "path"]
