version: "3.8"

services:
  flask-app:
    image: filesharing-webapp:t
    ports:
      - "5000:5000"
    volumes:
      - /host/folder:/container/folder
    entrypoint: ["python", "main.py","--path", "/container/folder"]
